photoboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),  # Используем класс-представление
    path('photos/', include('photos.urls', namespace='photos')),  # Добавляем namespace
    path('users/', include('users.urls', namespace="users")),
]

# Обслуживание статических и медиа файлов
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    # Для продакшена (Railway)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.urls import path, register_converter, re_path
from . import views, converters

register_converter(converters.StringConverter, 'string')
register_converter(converters.YearConverter, 'year')
app_name = 'photos'  # Определяем namespace

urlpatterns = [
    # CBV
    path('', views.PhotoListView.as_view(), name='photo_list'),
    path('<int:pk>/', views.PhotoDetailView.as_view(), name='photo_detail'),
    path('photo/<slug:slug>/',
         views.PhotoDetailView.as_view(),
         name='photo_detail_slug'),
    path('photo/<slug:slug>/edit/',
         views.EditPhotoView.as_view(),
         name='edit_photo'),
    path('photo/<slug:slug>/delete/',
         views.DeletePhotoView.as_view(),
         name='delete_photo'),
    path('year/<year:year>/',
         views.PhotosByYearView.as_view(),
         name='photos_by_year'),
    path('tag/<slug:tag_slug>/',
         views.PhotosByTagView.as_view(),
         name='photos_by_tag'),
    path('category/<slug:category_slug>/',
         views.PhotosByCategoryView.as_view(),
         name='photos_by_category'),
    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('redirect/',
         views.RedirectToHomeView.as_view(),
         name='redirect_to_home'),
    # Простой View
    path('simple/', views.SimplePhotoView.as_view(), name='simple_photo_view'),
    # Upload View
    path('upload/', views.UploadPhotoView.as_view(), name='upload_photo'),
    path('upload-non-model/',
         views.UploadPhotoNonModelView.as_view(),
         name='upload_photo_non_model'),
    # Кириллица
    re_path(r'^tag/(?P<tag_slug>[\w\-а-яё]+)/$',
            views.PhotosByTagView.as_view(),
            name='photos_by_tag'),
    # Маршруты для комментариев
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('comment/<int:comment_id>/edit/', views.edit_comment, name='edit_comment'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    # Аутентификация
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    
    # Профили
    path('profile/', views.profile_view, name='profile_view'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/<str:username>/', views.edit_profile, name='edit_profile_user'),
    path('profile/<str:username>/', views.profile_view, name='profile_view_user'),
    
    # Смена пароля
    path('password-change/', 
         auth_views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url='/users/password-change/done/'
         ), 
         name='password_change'),
    path('password-change/done/', 
         auth_views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'
         ), 
         name='password_change_done'),
    
    # Восстановление пароля
    path('password-reset/', 
         views.CustomPasswordResetView.as_view(), 
         name='password_reset'),
    path('password-reset/done/', 
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ), 
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url='/users/password-reset/complete/'
         ), 
         name='password_reset_confirm'),
    path('password-reset/complete/', 
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ), 
         name='password_reset_complete'),
    
    # Административные функции
    path('all-profiles/', views.all_profiles_view, name='all_profiles'),
    path('moderator-panel/', views.moderator_panel, name='moderator_panel'),
    path('manage-roles/<int:user_id>/', views.manage_user_roles, name='manage_user_roles'),
]

photos/views.py
from django.db.models.functions import ExtractYear
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.files.storage import default_storage
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from .models import Photo, Category, PhotoCategory, Comment, PhotoLike
from .forms import CommentForm, PhotoForm, PhotoUploadForm
from .utils import DataMixin
from django.db.models import Count, Avg, Max, Value, FloatField, ExpressionWrapper, IntegerField, F
from datetime import date


class RedirectToHomeView(View):
    """Перенаправление на главную страницу"""

    def get(self, request, *args, **kwargs):
        return redirect('photos:photo_list')


class SimplePhotoView(View):
    """Простой View для работы с фотографиями"""
    
    def get(self, request, *args, **kwargs):
        """Handle GET requests - show simple photo info"""
        photos_count = Photo.objects.count()
        latest_photo = Photo.objects.order_by('-uploaded_at').first()
        
        context = {
            'photos_count': photos_count,
            'latest_photo': latest_photo,
            'message': 'Простой View для работы с фотографиями'
        }
        
        return render(request, 'photos/simple_view.html', context)
    
    def post(self, request, *args, **kwargs):
        """Реализация POST запроса"""
        # Простая обработка POST запроса
        action = request.POST.get('action', '')
        
        if action == 'refresh_stats':
            messages.success(request, 'Статистика обновлена!')
        elif action == 'clear_cache':
            messages.info(request, 'Кэш очищен!')
        else:
            messages.warning(request, 'Неизвестное действие!')
            
        return self.get(request, *args, **kwargs)


class UploadPhotoView(DataMixin, CreateView):
    """Загрузка фотографии"""
    model = Photo
    form_class = PhotoForm
    template_name = 'photos/upload_photo.html'
    success_url = reverse_lazy('photo_list')
    title_page = 'Загрузить фотографию'

    def __init__(self):
        super().__init__()
        self.extra_context.update({
            'form_type':
            'ModelForm',
            'form_description':
            'Форма связанная с моделью (использует upload_to)'
        })

    def form_valid(self, form):
        try:
            photo = form.save(commit=False)
            if self.request.user.is_authenticated:
                photo.uploaded_by = self.request.user
            photo.save()

            tags_text = form.cleaned_data.get('tags', '')
            if tags_text:
                tags_list = [
                    tag.strip() for tag in tags_text.split(',') if tag.strip()
                ]
                photo.tags.add(*tags_list)

            self.success_url = reverse_lazy('photos:photo_detail_slug',
                                            kwargs={'slug': photo.slug})
            return super().form_valid(form)
        except Exception as e:
            messages.error(self.request, f'Ошибка при загрузке: {str(e)}')
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Пожалуйста, исправьте ошибки в форме.')
        return super().form_invalid(form)


class UploadPhotoNonModelView(DataMixin, FormView):
    """Загрузка фотографии с использованием обычной формы"""
    form_class = PhotoUploadForm
    template_name = 'photos/upload_photo_non_model.html'
    success_url = reverse_lazy('photo_list')
    title_page = 'Загрузить фотографию (обычная форма)'

    def __init__(self):
        super().__init__()
        self.extra_context.update({
            'form_type':
            'Form',
            'form_description':
            'Форма НЕ связанная с моделью (также использует upload_to)'
        })

    def form_valid(self, form):
        try:
            # Создание объекта Photo без сохранения в базу данных
            photo = Photo(title=form.cleaned_data['title'],
                          description=form.cleaned_data['description'],
                          image=form.cleaned_data['image'],
                          category_type=form.cleaned_data['category_type'])

            if self.request.user.is_authenticated:
                photo.uploaded_by = self.request.user

            photo.save()

            # Работа с тегами
            tags_text = form.cleaned_data.get('tags', '')
            if tags_text:
                tags_list = [
                    tag.strip() for tag in tags_text.split(',') if tag.strip()
                ]
                photo.tags.add(*tags_list)

            self.success_url = reverse_lazy('photos:photo_detail_slug',
                                            kwargs={'slug': photo.slug})
            return super().form_valid(form)
        except Exception as e:
            messages.error(self.request, f'Ошибка при загрузке: {str(e)}')
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Пожалуйста, исправьте ошибки в форме.')
        return super().form_invalid(form)


class EditPhotoView(DataMixin, LoginRequiredMixin, UpdateView):
    """Редактирование фотографии"""
    model = Photo
    form_class = PhotoForm
    template_name = 'photos/edit_photo.html'
    slug_url_kwarg = 'slug'
    title_page = 'Редактировать фотографию'

    def get_success_url(self):
        return reverse_lazy('photos:photo_detail_slug',
                            kwargs={'slug': self.object.slug})

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.uploaded_by != self.request.user and not self.request.user.is_staff:
            messages.error(
                self.request,
                'У вас нет прав для редактирования этой фотографии.')
            raise Http404("Нет прав для редактирования")
        return obj

    def get_initial(self):
        """Заполнение полей формы из объекта модели"""
        initial = super().get_initial()
        initial['tags'] = ', '.join(
            [tag.name for tag in self.object.tags.all()])
        return initial

    def form_valid(self, form):
        try:
            updated_photo = form.save()

            # Редактирование тегов
            tags_text = form.cleaned_data.get('tags', '')
            updated_photo.tags.clear()
            if tags_text:
                tags_list = [
                    tag.strip() for tag in tags_text.split(',') if tag.strip()
                ]
                updated_photo.tags.add(*tags_list)

            messages.success(self.request, 'Фотография успешно обновлена!')
            return super().form_valid(form)
        except Exception as e:
            messages.error(self.request, f'Ошибка при обновлении: {str(e)}')
            return self.form_invalid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Пожалуйста, исправьте ошибки в форме.')
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        """Добавляем объект фотографии в контекст"""
        context = super().get_context_data(**kwargs)
        context['photo'] = self.object
        return context


class DeletePhotoView(DataMixin, DeleteView):
    """Удаление фото"""
    model = Photo
    template_name = 'photos/delete_photo.html'
    slug_url_kwarg = 'slug'
    success_url = reverse_lazy('photo_list')
    title_page = 'Удалить фотографию'

    def get_object(self, queryset=None):
        """Get photo object without user permission checks"""
        obj = super().get_object(queryset)
        if obj.uploaded_by != self.request.user and not self.request.user.is_staff:
            messages.error(self.request,
                           'У вас нет прав для удаления этой фотографии.')
            raise Http404("Нет прав для удаления")
        return obj

    def delete(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            # Удаляем файл с сервера
            if self.object.image:
                default_storage.delete(self.object.image.name)

            success_url = self.get_success_url()
            self.object.delete()
            messages.success(request, 'Фотография успешно удалена!')
            return redirect(success_url)
        except Exception as e:
            messages.error(request, f'Ошибка при удалении: {str(e)}')
            return redirect('photos:photo_detail_slug', slug=self.object.slug)


class PhotosByYearView(DataMixin, ListView):
    """Список фото по годам"""
    model = Photo
    template_name = 'photos/photos_by_year.html'
    context_object_name = 'photos'

    def get_queryset(self):
        year = self.kwargs['year']
        return Photo.objects.filter(uploaded_at__year=year)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = self.kwargs['year']
        years = Photo.objects.dates('uploaded_at',
                                    'year').values_list('uploaded_at__year',
                                                        flat=True)
        return self.get_mixin_context(context,
                                      year=year,
                                      years=years,
                                      title=f'Фотографии за {year} год')


class PhotosByCategoryView(DataMixin, ListView):
    """Список фото по категориям"""
    model = Photo
    template_name = 'photos/photos_by_category.html'
    context_object_name = 'photos'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        return Photo.objects.filter(category_type=category_slug.upper())

    def get_context_data(self, **kwargs):

photos/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Фотогалерея{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <nav class="main-nav">
        <div class="container">
            <ul class="nav-list">
                <li class="home-icon">
                    <a href="{% url 'photos:photo_list' %}">
                        <i class="fas fa-home"></i> Главная
                    </a>
                </li>
                <li><a href="{% url 'photos:upload_photo' %}" class="btn btn-success">Загрузить фото</a></li>
                <li><a href="{% url 'photos:photo_list' %}">Все фотографии</a></li>  
                <li><a href="{% url 'photos:tag_list' %}">Теги</a></li>
                <li><a href="{% url 'photos:stats' %}">Статистика</a></li>
                
                <!-- Пользовательское меню -->
                <li class="ms-auto user-menu">
                    {% if user.is_authenticated %}
                        <div class="user-dropdown">
                            <button class="user-menu-btn" type="button">
                                {% if user.profile.avatar %}
                                    <img src="{{ user.profile.avatar.url }}" alt="Аватар" class="user-avatar-small">
                                {% else %}
                                    <i class="fas fa-user"></i>
                                {% endif %}
                                {{ user.get_full_name|default:user.username }}
                                <i class="fas fa-chevron-down"></i>
                            </button>
                            <div class="user-dropdown-menu">
                                <a href="{% url 'users:profile_view' %}">
                                    <i class="fas fa-user"></i> Мой профиль
                                </a>
                                <a href="{% url 'users:edit_profile' %}">
                                    <i class="fas fa-edit"></i> Редактировать профиль
                                </a>
                                <a href="{% url 'users:password_change' %}">
                                    <i class="fas fa-key"></i> Сменить пароль
                                </a>
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'users:logout' %}">
                                    <i class="fas fa-sign-out-alt"></i> Выйти
                                </a>
                                {% if perms.users.can_view_all_profiles %}
                                    <div class="dropdown-divider"></div>
                                    <a href="{% url 'users:all_profiles' %}">
                                        <i class="fas fa-users"></i> Все профили
                                    </a>
                                {% endif %}
                                {% if user.groups.all %}
                                    {% for group in user.groups.all %}
                                        {% if group.name == "Модераторы" %}
                                            <div class="dropdown-divider"></div>
                                            <a href="{% url 'users:moderator_panel' %}">
                                                <i class="fas fa-shield-alt"></i> Панель модератора
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                                
                                {% if user.is_staff %}
                                    <div class="dropdown-divider"></div>
                                    <a href="/admin/">
                                        <i class="fas fa-cog"></i> Админ-панель
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    {% else %}
                        <div class="auth-buttons">
                            <a href="{% url 'users:login' %}" class="btn btn-primary">
                                <i class="fas fa-sign-in-alt"></i> Войти
                            </a>
                            <a href="{% url 'users:register' %}" class="btn btn-success">
                                <i class="fas"></i> Регистрация
                            </a>
                        </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <main>
        {% if messages %}
            <div class="container mt-3">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div class="footer-content">
            <div class="footer-info">
                <h3>Фотогалерея</h3>
                <p>Делитесь своими лучшими моментами</p>
            </div>
            <div class="footer-links">
                <h3>Навигация</h3>
                <a href="{% url 'photos:photo_list' %}">Все фотографии</a>
                <a href="{% url 'photos:upload_photo' %}">Загрузить фото</a>
                <a href="{% url 'photos:tag_list' %}">Теги</a>
                <a href="{% url 'photos:stats' %}">Статистика</a>
            </div>
            <div class="footer-social">
                <h3>Аккаунт</h3>
                {% if user.is_authenticated %}
                    <a href="{% url 'users:profile_view' %}">Мой профиль</a>
                    <a href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'users:login' %}">Войти</a>
                    <a href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

photos/templates/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="auth-form">
    <h2>Вход</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Имя пользователя:</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">Пароль:</label>
            <input type="password" name="password" id="password" required>
        </div>
        <button type="submit">Войти</button>
    </form>
    <p>Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></p>
</div>
{% endblock %}

photos/templates/register.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="auth-form">
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Имя пользователя:</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" required>
        </div>
        <div class="form-group">
            <label for="password1">Пароль:</label>
            <input type="password" name="password1" id="password1" required>
        </div>
        <div class="form-group">
            <label for="password2">Подтвердите пароль:</label>
            <input type="password" name="password2" id="password2" required>
        </div>
        <button type="submit">Зарегистрироваться</button>
    </form>
    <p>Уже есть аккаунт? <a href="{% url 'login' %}">Войти</a></p>
</div>
{% endblock %}